def run(self):
    raise TestException('Something went wrong!')
