{
  ExceptionalClosure<Integer,IOException> work=createMock(EXC_INT_CLOSURE_CLZ);
  work.execute(1);
  RuntimeException runtimeException=new Thrown();
  EasyMock.expectLastCall().andThrow(runtimeException);
  control.replay();
  Function<Integer,Void> workFunction=Closures.asFunction(work);
  try {
    workFunction.apply(1);
  }
 catch (  Thrown e) {
    assertSame(runtimeException,e);
  }
}
