def run(self):
    raise TestException
