{
  return failure.getException() instanceof AssertionError;
}
